In [44]:
import numpy as np

array1 = np.array(range(30))
array2 = np.array([2,3,5])
#1.
with open("D06.npz", "wb") as f:
    np.savez(f, array1, array2)
nnpzfile= np.load("D06.npz")
nnpzfile.files
print(nnpzfile["arr_0"])
print(nnpzfile["arr_1"])  
print("成功讀取")
#2.
npzfile= np.load("multi_array.npz")
npzfile.files
with open("D06.npz", "wb") as f:
    np.savez(f, array1,array2,
             npzfile["array1"],
            npzfile["array2"],
            npzfile["array3"])
new_npzfile= np.load("D06.npz")
new_npzfile.files
print(new_npzfile["arr_0"]) 
print(new_npzfile["arr_1"]) 
print(new_npzfile["arr_2"]) 
print(new_npzfile["arr_3"]) 
print(new_npzfile["arr_4"]) 

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]
[2 3 5]
成功讀取
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]
[2 3 5]
[0 1 2 3 4 5 6 7 8 9]
[1 2 3]
[4.56248420e-01 5.41646880e-01 3.77180401e-01 8.04260599e-01
 2.89279193e-01 2.16416111e-02 4.57347946e-01 4.36980707e-01
 5.41068344e-04 1.73563154e-01]
